### ISSUE TITLE
Binding not working from viewmodel.cs to .dotcontrol

### ISSUE THREAD

**Issue by nagulapallinaveen** [riganti/dotvvm#1407]
`Library.dotcontrol
@viewModel System.Object, mscorlib
@baseType Mit.Portal.Controls.LibraryViewModel, IPS

<script src="{value: "../js/picker.js?x=" + jsRefreshKey }" type="text/javascript"></script>

LibraryViewModel.cs
namespace Mit.Portal.Controls.
{
    public class LibraryViewModel : DotvvmMarkupControl
    {
        public string jsRefreshKey
        {
            get { return (string)GetValue(jsRefreshKeyProperty); }
            set { SetValue(jsRefreshKeyProperty, value); }
        }
        public static readonly DotvvmProperty jsRefreshKeyProperty
                = DotvvmProperty.Register<string, UCLibraryViewModel>(c => c.jsRefreshKey, "jsRefreshKey");

        public void OnPreInit(IDotvvmRequestContext context)
        {
            jsRefreshKey = DateTime.Now.ToString("yyyyMMdd");
        }
      }
}`

not able to fetch the value of from jsRefreshKey from cs to dotcontrol. Binding is not working

System.ExceptionCould not resolve identifier 'jsRefreshKey'.
DotVVM.Framework.Binding.BindingPropertyExceptionUnable to get property KnockoutExpressionBindingProperty: Could not resolve identifier 'jsRefreshKey'. Binding: {value: "../js/picker.js?x=" + jsRefreshKey }. Property path: KnockoutExpressionBindingProperty, KnockoutJsExpressionBindingProperty, CastedExpressionBindingProperty.

**Comment by exyi** [comment]
Tomas is right, if I understand your problem.

However, why are adding this jsRefreshKey to the `script` tag? If you want to serve a piece of JS, consider using DotVVM resources, it will handle caching and cache invalidation automatically for you (see https://www.dotvvm.com/docs/4.0/pages/concepts/script-and-style-resources/overview)

In DotVVM startup:

```
config.Resources.RegisterScriptFile(name: "picker.js", filePath: "~/js/picker.js")
```

In dothtml file:

```
<dot:RequiredResource Name=picker.js />
```


And even if you didn't want to use dotvvm resources, just use the `Cache-Control: max-age=CacheTimeout` header for cache invalidation instead of this complex way. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
