### ISSUE TITLE
The control <dot:MultiView> could not be resolved! 

### ISSUE THREAD

**Issue by DmitryChekh** [riganti/dotvvm#1408]
Hello! I have this template 
```
<dot:MultiView ID="Views" runat="server">
    <asp:View ID="ViewSchoolBrowse" OnActivate="ViewSchoolBrowse_OnActivate" runat="server">
...
    </asp:View>
    <asp:View ID="ViewSchoolView" OnActivate="ViewSchoolView_OnActivate" runat="server">
...
    </asp:View>
</dot:MultiView>
```
I didn't find MultiView component or similar in DotVVM. Can you help me to migrate the code. Is it possible?

**Comment by exyi** [comment]
If I understand what MultiView did in WebForms - it's just choosing which of the views will be rendered. You can simply use `Include={value: Condition}` property in DotVVM:

```

    <div IncludeInPage={value: ViewSchoolBrowse}>
...
    </div>
    <div IncludeInPage={value: !ViewSchoolBrowse}>
...
    </div>

```

And add the `ViewSchoolBrowse` property to the view model. In case you have more than 2 possible states, you can use an enum instead of boolean. Note that if you don't need to switch between "views" after the page is loaded, you can use a `{resource: ViewSchoolBrowse}` binding, that will avoid sending both views to the client.

Feel free to reopen if this didn't solve your problem.
