### ISSUE TITLE
Remove the DataContext property from markup of dot:GridViewColumn

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#153]
`<dot:GridViewTemplateColumn DataContext="{value:  context}" >`

This causes an exception when some command is used in ContentTemplate element. This markup doesn't make sense. Please remove the property from markup.

**Comment by exyi** [comment]
Sorry, it is pretty much impossible. :( The property is inherited from DotvvmBindableObject.

**Comment by quigamdev** [comment]
Are you able to remove this property at least from IntelliSense for this case?

**Comment by exyi** [comment]
Yes of course. Just a little if...

**Comment by Mylan719** [comment]
I don't really like how unsystematic this is. Maybe we could add some mechanism to disable inherited property on a control. So that both the framework and the extension would behave accordingly. Adding ifs for a particular case is a step on a path of suffering in my opinion.

**Comment by tomasherceg** [comment]
1. This issue is more complex than just hiding the `DataContext` property from some controls - there are several other properties that just do not make sense on various places. 
We should try to create a list of such cases and solve them together as it may lead to another things in the framework and controls that might require to be updated.

2. Maybe we can make the `DataContext` property protected on `DotvvmBindableBase` control and hide it with the public one in the `DotvvmControl`.

**Comment by tomasherceg** [comment]
We should prevent setting the `DataContext` property using the `ValidateUsage`.

**Comment by exyi** [comment]
Added validation for this case in #1081
