### ISSUE TITLE
List<object> in the viewmodel makes crashes without error on the client

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1555]
In one test project, we had `List<object>` in the ViewModel.
Although this is not a good idea and is not officially supported, the page rendered, but failed to apply server response to the ViewModel on the postback without producing any error. 
We should definitely add error handling to deserialization so the JS errors are emitted.

**Comment by exyi** [comment]
This is probably a regression in 4.1 in #1536 and it will likely occur in other cases where inheritance is used. It crashes since `mapUpdatableProperties` is touching type metadata before new type metadata is added.

A workaround would be to add a dummy property in the root viewmodel for all types which may be added to the collection (it can be null, just its type matters)
