### ISSUE TITLE
DotVVM for Visual Studio: The 'DotvvmPackage' package did not load correctly in VS 17.5

### ISSUE THREAD

**Issue by gkirk90** [riganti/dotvvm#1601]
I am still seeing an issue loading the extension in 17.5 and have tried 17.5.1 after upgrading to extension version 4.0.556
DotVVM for Visual Studio: The 'DotvvmPackage' package did not load correctly in VS 17.5

SetSite failed for package [DotvvmSubTypePackage]Source: 'DotVVM.Integration.VisualStudio.DotvvmSubType' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=17.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at DotVVM.Integration.VisualStudio.DotvvmSubType.ProjectExtensions.DotvvmSubTypePackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by acizmarik** [comment]
I just tested 4.0.556.0 together with Visual Studio 17.5.1 and it works on my machine. In order to debug this issue I am going to need more information.

* Perform a clean installation of DotVVM Extension (remove previous installation and after that install again)
  * Sometimes old assemblies remain in wrong places
* If the step above did not help, enable assembly bind logging and run the Visual Studio again
  * Exception should now provide additional info why the binding failed
  * Reference: https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by gkirk90** [comment]
A clean installation appears to have solved the issue, thanks for the help.
