### ISSUE TITLE
Processing validation results - more violations per property

### ISSUE THREAD

**Issue by MarekPokornyOva** [riganti/dotvvm#164]
Hello,
I've found something I don't know it's a bug or desired design behavior. It's about validation results.

Let's say I have a class used in a view model
```
public class User
{
	[StringLength(255, MinimumLength=8)]
	[Required]
	[Phone]
	public string Password { get; set; }
}
```

... and a template ...
```
Password: <dot:TextBox Text="{value: User.Password}" />
<dot:ValidationSummary IncludeErrorsFromChildren="true"/>
```

Well, maybe it's not the best example but still, the point is the property has more validators configured.

Now, when a page tries to update entered data ("pass" value), more validator fails and both Phone and StringLength validation error are send to page from server.
The server response might looks like:
```
{
  "modelState": [
    {
      "propertyPath": "User().Password",
      "errorMessage": "The field Password must be a string with a minimum length of 8 and a maximum length of 255."
    },
    {
      "propertyPath": "User().Password",
      "errorMessage": "The Password field is not a valid phone number."
    }
  ],
  "action": "validationErrors"
}
```

Looks good, doesn't it? Two validation violations, two errors sent to the page.

But ValidationSummary control contains only error message - the last one in the "modelState" array.

If I understand (from targetObservable["validationError"] and ValidationError.getOrCreate(observable);) correctly, the framework design says the functionality is fine. But is it desired behavior? I (as a user) would like to see all conditions at once. I (as a developer) would like to show all conditions at once. Is it possible to do so in an easier way than to significantly rewrite DotvvmValidation?

Thanks you spent time with reading and thinking about
Marek Pokorny

**Comment by tomasherceg** [comment]
The thing is that we translate some validation rules in javascript, but some of them cannot be translated. So when the user clicks the button, the errors validated on the client appear. When these issues are fixed, the errors from the server are displayed.

We are aware of this issue, however the solution would be quite complicated. We plan to add an option to disable the validation on the client side, however this will affect many things including the serializer which crashes when there is e.g. a string value in the int field. 

But I don't have another idea how to resolve this issue because some validation just cannot be done on the client side. If you have any suggestions, we are listening.

**Comment by exyi** [comment]
@tomasherceg I thing the problem is that both errors come from server, but only one is displayed. We can probably use collection for each property or combine errors into single one.

**Comment by exyi** [comment]
I have fixed the validation to support more error per property. @MarekPokornyOva could you please try if it does what you'd expect?

**Comment by MarekPokornyOva** [comment]
Works great! Thank you for the modification.
Now also possible to nest an UL element with foreach binding to customize showing validation violations.
