### ISSUE TITLE
Exception filter handling and PreRender method not working

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#165]
If custom method throw exception in PreRender event:

        public override Task PreRender()
        {
            throw new UIException("message");
        }        
   
       public class UIExceptionFilter : ExceptionFilterAttribute
       {
        protected override void OnException(IDotvvmRequestContext context, ActionInfo actionInfo, Exception ex)
        {
            if (ex is UIException)
            {
                var model = context.ViewModel as BaseVM;
                model?.Alert(ex.Message, AlertType.Error);
                context.IsCommandExceptionHandled = true;
            }
        }
    }
'

Exception handling not working. Is here any workaround?

Thanks

**Comment by tomasherceg** [comment]
The problem is that exception filters are designed to only wrap up exceptions in commands. We don't have any method that is called when the exception occurs up elsewhere. 

There are two options:

1) Rename the `OnException` method to `OnCommandException` which is better, and add another method `OnPageException` which will be called for all other exceptions.

2) Don't mess it up with action filters and use another mechanism for this.

**Comment by exyi** [comment]
I have renamed OnException to OnCommandException, because it was misleading. I think having the OnPageException is good idea, but it is bit more complicated to implement.
