### ISSUE TITLE
Problem with generating dotvvm.postbackScript() function

### ISSUE THREAD

**Issue by darilek** [riganti/dotvvm#179]
Hi,
I'm trying start with implementing DotVVM wrappers over DevExpress JS Widgets (DevExtreme suite). I've started with DxButton widget :-) I have problem with generating correct calling of `dotvvm.postbackScript()` function through the `KnockouHelper.GenerateClientPostBackScript()` method
Current generated code:

``` html
<div data-bind="dxButton: {
   text: 'Generate random value',
   onClick: function(e) { 
      dotvvm.postbackScript("TestCommand()")('root', this, [], '', false, "$root", null, null);
      return false;}
   }}"
>
</div>
```

Expected (functional code)

``` html
<div data-bind="dxButton: {
   text: 'Generate random value',
   onClick: function(e) { 
      dotvvm.postbackScript("TestCommand()")('root', e.element[0], [], '', false, "$root", null, null);
      return false;}
   }}"
>
</div>
```

I think, helper method should accept custom element accessor parameter - somethink like

``` c#
public static string GenerateClientPostBackScript(
   string propertyName,
   ICommandBinding expression,
   DotvvmControl control,
   string elementAccesor = "this",  /* this is new parameter */
   bool useWindowSetTimeout = false,
   bool? returnValue = false, 
   bool isOnChange = false
) 
{
   ...
}
```

**Comment by exyi** [comment]
When you look at https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Controls/KnockoutHelper.cs#L74, it seems pretty easy to do - the solution will probably work fine for `command` bindings. Unfortunately things are not that easy if you'd like to support `staticCommand` bindings because they use `this` once more. I'd recommend you to copy-paste this helper method to your project and replace [this](https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Controls/KnockoutHelper.cs#L74) with whatever you want as a quick&dirty solution.

And we should probably rewrite how commands are rendered. @tomasherceg you wanted the api commands, which will probably also need bit more infrastructure.

**Comment by tomasherceg** [comment]
Until we'll figure out what to do, I would suggest doing this quick fix - use apply to inject the element instead of this.

```
<div data-bind="dxButton: {
   text: 'Generate random value',
   onClick: function (e) { 
      (function () {
        dotvvm.postbackScript("TestCommand()")('root', this, [], '', false, "$root", null, null); 
        return false;
      }).apply(e.elements[0]);
      return false;
   }
}">
</div>
```

About the `GenerateClientPostBackScript` method, it sucks because it has many parameters.
We should do the following steps:

1. We should refactor the method so it takes one argument of `ClientPostBackSettings`, which will contain all these properties.

2. We can add the ElementAccessorExpression property with default value of `this`.

3. What is the real issue, is that the postback should return some kind of Promise because in some controls, we need to do the postback and invoke some callback after is it finished. We only have global client postback events which are not good for this purpose.

**Comment by darilek** [comment]
@tomasherceg thanks for tip. The apply/call wrapper over dotvvm.postbackScript() works perfectly

**Comment by tomasherceg** [comment]
I am reopening this issue since we should discuss how postback scripts are generated and perhaps modify the API so the function GenerateClientPostBackScript doesn't have thousand parameters.

**Comment by exyi** [comment]
Ok, I have created options class for this, but still, the thisParameter does not work for staticCommands :(
