### ISSUE TITLE
Redirect issue with SpaContentPlaceHolder

### ISSUE THREAD

**Issue by ndfra** [riganti/dotvvm#185]
Maybe I have been experienced an issue with redirect methods and SpaContentPlaceHolder.

I'll try to describe better my solution and scenario:

1) I have a master page with SpaContentPlaceHolder
2) I have 2 views with the following routes: 
      config.RouteTable.Add("Login", "login", "Views/loginView.dothtml");
      config.RouteTable.Add("Home", "", "Views/homeView.dothtml");
3) The view model of home view contains the Authorize attribute
4) Inside the LoginViewModel I have the method Login that (in case of username and password valid) redirect to home view
5) I have been tried both RedirectToUrl and RedirectToRoute but the generated address seems not wel formed (url/login#!home)
6) I tried both with rc2 nuget version and trunk version

is it my fault or that behavior is strange?

**Comment by exyi** [comment]
If I understand you correctly, I suppose you are redirected from homepage to the login page by ordinary http redirection. Then from the login page, you are redirecting by Spa redirect back to home. So the framework has added `#!...` at the end of url. It can't change the path in url, since it will reload the page so `/login` remains here. You can probably solve it by not using Spa for login page or not using [Authorize] on home page.

**Comment by tomasherceg** [comment]
If you use OWIN Cookie Security (or other OWIN Security authentication middleware), make sure you override the OnApplyRedirect function in the OWIN configuration:

```
app.UseCookieAuthentication(new CookieAuthenticationOptions()
{
    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    LoginPath = new PathString("/login"),       // don't use ~/login here - the ~ in URLs is a DotVVM feature, OWIN security doesn't know it
    Provider = new CookieAuthenticationProvider()
    {
        OnApplyRedirect = e => DotvvmAuthenticationHelper.ApplyRedirectResponse(e.OwinContext, e.RedirectUri)
    }
});
```

DotVVM must make the redirects in different way because of AJAX calls. That's why you need to tell OWIN Security how the redirects shall be performed.

**Comment by ndfra** [comment]
Hi,

Yes I use OWIN and I have already configured the authentication in that way.
The redirect from Home view to Login view is automatic (thru the configuration above and Authorize attribute) and works fine, but my redirect from LoginViewModel does not work at all

**Comment by tomasherceg** [comment]
Thank you, I have succeeded to replicate the issue. We'll fix it as soon as possible and let you know.

**Comment by tomasherceg** [comment]
Hi, we have just published DotVVM.1.0.0.7-rc2 on official Nuget. This redirect issue is fixed in this version. Sorry for the delay.
