### ISSUE TITLE
Capabilities of static binding

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#187]
I wonderwat you can and can't do with static command binding. I would like all its features documented.
Is practice like this possible?
```csharp
{staticCommand: 
this.SubViewModel.Property 
= NameSpace1.Namespace2.Type1.StaticFunc1() 
+ NameSpace3.Namespace4.Type2.StaticFunc2()}
```
I would like to know what it can and can not do namely to make framework behavior consistent with extension intellisense.

**Comment by tomasherceg** [comment]
I think we need to support only two variants of `staticCommand`:

`{staticCommand: Something...Something.Function(Arguments)}`

`{staticCommand: Something = Something...Something.Function(Arguments)}`. 

I don't need any binary or unary operators, just FunctionCall or Something = FunctionCall. 
I don't want the users write complicated expressions in views because it is a bad practice.

**Comment by exyi** [comment]
It works :) However it will raise multiple http requests because the functions are executed on server separately and the logic in the binding is executed on client. I think it should be supported (although not recommended) as you may want to do something like `{staticCommand: Something = "hello" + Function()}` or whatever similar.
