### ISSUE TITLE
String.Format in value bindings

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#195]
We'd like to support string formatting capabilities in `value` and `resource` bindings. We are considering how the syntax should like. We want to use .NET format strings so the formatting works the same way on both server side and client side.

The most preferred solution is to keep the .NET way, so the binding would look like this:

`{value: string.Format("Test {0} {1:yyyy/M/d}", Id, CreatedDate)}

However, we need to decide how the function should be named:
- `string.Format` - my personal favorite, everybody understands what it means, the problem is that it's quite long and the users will expect that other .NET functions will work in the bindings too.
- `_dotvvm.format` - maybe it would be a good idea to introduce the `_dotvvm` alias which will contain this kind of functions. We have several controls which render their own functions (e.g. the RouteLink uses the buildRouteUrl function) and it is not possible to use this function from the bindings. If we place it in the `_dotvvm` namespace, it would be possible to create another controls which build routes pretty easily.
- Someone also brought an idea that the format function could be instance, so the binding would look like this `value: "Test {0} {1:yyyy/M/d}".Format(Id, CreatedDate)`

Other ideas?

**Comment by exyi** [comment]
Dup of #141, I'm closing it, as you have written more info here :).
I support the string.Format - it is easy to implement, to understand and to learn. The documentation could be just "You can use string.Format." not "but it is called ...". Maybe as an alternative we could support the extension method `"...".Format()`.
I was also thinking about format operator similar to the one in Powershell, but I don't really think it is the best idea as you may want to pass multiple parameters to the format method.

**Comment by darilek** [comment]
I like the .net shorthand syntax for string format ($"...") but it is not easy implement it on client side :-( 

I vote for shorthand of _dotvvm static class. May be simple "dot"?

**Comment by tomasherceg** [comment]
Yes, I was thinking about the $ syntax too, but we'll still need string.Format because I need to use it also in the resource bindings: `{resource: string.Format(ResourceFile.SomeItem, _this.Title)}`.

**Comment by djanosik** [comment]
I vote for `$""` syntax and for `. Format(...)` instance / extension method. Is there some way to integrate Humanizer-like solution?

**Comment by exyi** [comment]
@djanosik It is possible to extend ;). Currently bindings can contain call to any method, humanizer is no exception, but there are some pitfalls:
* value binding has to be translatable to Javascript, so you have to register how to translate the call to knockout binding. It is pretty easy to register it, but the api will probably change because the translator to Javascript is bit proof-of-conceptish.
* Extension methods are not supported, they have to be called like static. But it should not be that hard to implement them.

**Comment by darilek** [comment]
$"" syntax is nice,but back to the reality :-) The $ shorthand could conflict with jquery syntax. Also String.format could replace another implementation. IMHO _dotvvm alias should be easy to extend to other methods, not "format" only

**Comment by quigamdev** [comment]
I vote for _dotvvm alias. When we decide to add more functions, I think the best concept is to collect all these functions in one namespace.

**Comment by djanosik** [comment]
I think there will be no conflict in .dothtml and it can be translated to different JS expression (eg. custom function, ES6 template literal).

**Comment by quigamdev** [comment]
@djanosik I really don't like the ES6 template literal. It's not going to work in older browsers. In bindings, there cannot be used javascript directly so in my opinion to use $"" is ok. 

What to implement _dotvvm alias for function like string.Format and other functions and for string.Format allow to use $"" syntax. When both options are implemented, users can decide what to use by their preferences.

**Comment by exyi** [comment]
@darilek There will not be any conflict, it will not be problem to translate it correctly, @djanosik is right. Only problem is that I will have to implement another feature to the parser :).

I don't like the `_dotvvm` name, I'm my opinion it could be called just Dotvvm in PascalCase as we are used to from C#. And I don't see any reason why it can't be standart string.Format or the Format extension method. Maybe people could think that all other string methods are also supported, but they should know from linq providers that sometimes only certain methods are supported. Maybe we could also support some other methods, like stirng.IsNullOrWhitespace()

**Comment by quigamdev** [comment]
@exyi What about to use "dotvvm" only? DotVVM is namespace and Dotvvm is some hybrid. At least I think it should not be named as a namespace. If so, people will think its available from .cs files.
Actually "dotvvm" is name of JS variable. But still I think that it is more understandable.
What do you think?

**Comment by tomasherceg** [comment]
I want every system object that is used in bindings to start with underscore, like `_this`, `_root` etc. Therefore `_dotvvm`.

**Comment by quigamdev** [comment]
What about something like `{value: FirstName.Format("Welcome {0}") }` and  `{value: "John".Format("Welcome {0}") }` ? 
What do you think this option?

The third option seems to me be semantically wrong. I want to format the value, not the pattern. `value.Format(pattern)` seems to me better.

**Comment by tomasherceg** [comment]
No, it must be the opposite way - the format string can contain more placeholders and it wouldn't be possible to use more than one. Also, the Format method would have to be an extension method of System.Object, which I don't like.

**Comment by darilek** [comment]
@quigamdev :+1: I also vote for _dotvvm alias. And f
or the most used functions like format create special shorthands/aliases

**Comment by Mylan719** [comment]
I personaly would prefer both `string.Format` syntax and `$""` syntax sugar. Implementing string.Format function to be translatable to javascript is easy and it would serve as en example of how dotvvm can be extende by implementing custom function to javascript translators. I like this approach because it is the most general solution and there is plenty of space for future extendability should we or custommers decide they need it.
I like the `$""` because I don't think it would be that hard to implement. The parser is pretty nice and clean so I think it to be that much of a problem. Plus it's very convinient ;)
@tomasherceg I think starting dotvvm 'keywords' with underscore is a good idea to make it clear they are special objects and avoid conflicts or comfusion with other objects as it has been pointed out.
However I don't really like the idea of `_dotvvm` keyword as some kind of magic box for the few selected funtions that we decide to support. I find it way more confusing than calling those funtions in context on the context where they belong and where they would be expected eg. `string.Format`. 
I agree with @exyi said. Linq always complains about every function that it is not translatable to SQL. Message "Function is not translatable to javascript." I belive won't scare anyone, specially if they can implement the translator for it themselves.

**Comment by tomasherceg** [comment]
OK, let's split this to two things:

* We'll support `string.Format` in bindings and keep the syntax as is.

* We'll think about the extensibility of bindings, so anyone can add custom alias (like `_dotvvm`) and place there custom functionality. We'll need this later for the REST API integration and other features.

**Comment by exyi** [comment]
Mostly resolved by 8b9213447d6898eeec42f9c9bf042b21e5885a68, I have created new issue for the string interpolation #362
