### ISSUE TITLE
Running in Mono

### ISSUE THREAD

**Issue by CristianT** [riganti/dotvvm#207]
I'm not sure what you want to do with this information, but I got the framework running in a Raspberry Pi with Mono. I created a very simple project and some instructions showing how to do it:
https://github.com/CristianT/MonoWebApp

Main problems related to dotVVM were:
- the path separator, I had to use '/' in all the views and routes instead of '\'
- the data protector being null as already explaned here: https://github.com/riganti/dotvvm/pull/206
- the DataProtector again. Mono doesn't have an implementation of DpapiDataProtector so I had to include a custom one as described here: http://beginor.github.io/2015/04/08/using-microsoft-owin-auth-middleware-with-mono.html or here http://www.ryanmelena.com/2014/10/31/thinktecture-identityserver-v3-on-mono/

**Comment by tomasherceg** [comment]
Hi, thank you for the feedback, we are currently porting DotVVM to .NET Core and this kind of feedback is very helpful to us.

**Comment by exyi** [comment]
Thank you for that WebApp, it look pretty cool that it can run on RPi :)
You can actually try the dotnetcore branch, if you'd like to ;) You will be the first one to do it, however all samples but one are working properly. It will probably solve the problem with DataProtectors because .NET Core should not be dependent on Windows.
We tried to keep the path separator in mind and since the forward slash works correctly both on windows and unix we try to use it everywhere in the framework and VS Extension, here master page completion with forward slahses:
![image](https://cloud.githubusercontent.com/assets/7894687/16900039/a070769a-4c18-11e6-8cd4-5e39a23f3219.png)
I hope we have not forgotten any bad slash anywhere. If you'd find one report it here, please.

**Comment by CristianT** [comment]
I've been looking everywhere for a .NET Core version for ARM devices but there is none working, not even for Windows 10 IoT, that's where dotVVM comes in, it is the only possibility I found to develop a self hosted web app without having to handle all the model-view synchronization yourself.

**Comment by djanosik** [comment]
@CristianT .NET Core runtime for ARM is coming in Q4 2016 (resp. Q1 2017).

**Comment by tomasherceg** [comment]
Thank you for your idea, we have created a tutorial how to prepare a RPi device and how to create DotVVM application on Mono. 

https://www.dotvvm.com/blog/8/Running-DotVVM-with-Mono-on-Raspberry-PI-Build-Your-Own-Weather-Station

**Comment by CristianT** [comment]
Good job, thanks for mentioning my name.
I'm working on a web application for monitoring several IoT devices. The raspberry is the central server running dotvvm and mongodb. 
The connected devices are the raspberry itself, an arduino and a NodeMCU.
I hope I have a shareable prototype soon, I'll drop you a link when it i ready.

**Comment by tomasherceg** [comment]
If you want me to put a link on your Twitter, blog or something similar in the article, just let me know. I can add it there.
And thank your for this nice idea.
