### ISSUE TITLE
DataContext and RenderWrapperTag="false" cannot be set at the same time.

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#217]
I have this code
`<dot:Repeater DataSource="{value: DocumentButtons}" DataContext="{value: RightPanelDocumentsModel}" RenderWrapperTag="false">`

Could you allow this combination of properties? Is there way to change the repeater code design to allow  this?

**Comment by tomasherceg** [comment]
Originally I wanted to allow this, but there is an issue the users would hit. It is not easy to track and I think it would do more harm than good.

The problem occurs when you want to render the `<table>` and you don't use `<thead>` and `<tbody>` elements inside. Knockout comment syntax doesn't work because the web browser adds the `<tbody>` element itself and the opening comment is placed outside the `<tbody>` while the closing comment is placed inside. Knockout cannot match those and the data-binding breaks.

![ko](https://cloud.githubusercontent.com/assets/5599524/17397959/ac421296-5a3a-11e6-8f29-29567ff49035.png)

If you have `Repeater` set not to render the wrapper tag, and you place it inside the `<table>` element (or e.g. the `<bs:Table>`), it won't work.

We have two options how to fix this:

1. Either we can detect whether the parent element of the `Repeater` is the `<table>` element or a control that renders the `<table>` (this is where it gets really complicated).
Also we should go through the HTML specification and see if this can happen with another elements.

2. We can modify Knockout to match even these comments. It will be quite complicated and it would require a lot of effort.


Because there isn't a nice and easy solution, this use case is quite marginal and you can just use `DataSource={value: RightPanelDocumentsModel.DocumentButtons}`, I suggest keep the behavior as is. 

Maybe the future versions of Knockout will address this issue somehow and we get it resolved for free.
