### ISSUE TITLE
Intellisense for ResourceKeys (from .RESX) when using @resourceType

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#225]
Hi,
it will be fine to have intellisense for resource keys from .resx files with @resourceType directive.

**Comment by Mylan719** [comment]
Intellisense for resources is actually a package of several features. 
 1. In later versions of DotVVM `@resourceType` directive will be deprecated in favor of `@import` directive. The `@resourceType` directive usage was rather limited and since some bindings support static methods, there was also need for shortening full type names. `@import` directive is designed to work exactly as `using` in C# and will also support aliases. Eg. `@import Res = MyProject.Resources.Dashboard`. This will replace  `@resourceType` and `@resourceNamespace` functionality completely and it proved to be more general solution.
2. Intellisense for `@import` directive should suggest namespaces and types when writing full type name.
3. Intellisense for bindings will suggest aliases created using `@import` directive(s) and types from imported namespaces will also be suggested.

 This feature with resources in mind could be used something like this:
```html
@viewmodel Something, Something
@import Texts = MyProject.Resources.Dashboard
<div>
{{resource: Texts.HelloWorld}}
</div>
```
The `@import` feature itself should be in master already, and I will star to work on VS integration shortly so  you can expect the intellisense in near future.

**Comment by exyi** [comment]
DotVVM 1.0 should already support `@import <namespace>` and `@import Alias = <namespace>`.  Aliasing type name (`@import Alias = <TypeName>` ) was fixe today, you can expect it in the next release.

**Comment by tomasherceg** [comment]
We should review whether the VS Extension supports this, and close the issue in this case. @Mylan719

**Comment by exyi** [comment]
These directives are completely obsolete and probably does not work at all.
