### ISSUE TITLE
FileUpload - add validation of size of selected file

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#232]
Add property MaxSize and  Error template for validation of size of selected file.

**Comment by djanosik** [comment]
There is already the `UploadedFile.Accepted` property. It is set to `false` when the type of uploaded file is not allowed. We can probably extend it to also work with the `MaxSize` property.

- `false` when a file type is not allowed
- `false` when a file size exceeds the `MaxSize`
- `true` otherwise

Then we can add `UploadedFile.Error` property that will explain why the file was not accepted. It is up to developer to decide how to handle such files (display error, remove from files, upload anyway, ...). It sounds great, but implementation is a bit complicated.

The current `FileUpload` control is not designed to display status separately for each file. It would require some changes to HTML / CSS structure and it would break every UI using this control.

Can we do this now? Or does it make sense to implement only server-side part?

BTW: This feature is partially implemented in BP upload.

**Comment by quigamdev** [comment]
@djanosik Please implement only server-side part.

**Comment by djanosik** [comment]
Fixed in d080de05c9df7afc7a9b7531e08aecc092aa1570:

- `FileUpload.MaxFileSize`
- `UploadedFile.MaxSizeExceeded`
