### ISSUE TITLE
RedirectToRoute in PreRender does not use SPA route

### ISSUE THREAD

**Issue by AlistairClark7** [riganti/dotvvm#254]
If you want to redirect the user to a specific when they are logged in and go to the default route, it does not use the SPA path.

Code:

```
public override Task PreRender()
{
    if (IsLoggedIn)
    {
        Context.RedirectToRoute("MyLoggedInPage");
    }
    return base.PreRender();
}
```

The user ends up getting redirected to /MyLoggedInPage rather than /#!/MyLoggedInPage

**Comment by tomasherceg** [comment]
I think this behavior is correct. The problem is that in the first request, the user doesn't have the HTML of the page loaded (because it hasn't been rendered yet).
So, DotVVM redirects to `/MyLoggedInPage` which is correct and should render the SPA with the MyLoggedInPage inside the container.

If you need the URL to be `/#!/MyLoggedInPage`, you have to set the `PrefixRouteName` property on the `SpaContentPlaceHolder` to a route which should define the part of the URL before the `#` sign. 

A bad thing is that this causes another redirect, so you will need 3 requests to do that, but I am afraid that currently there is no other way to do it.
