### ISSUE TITLE
Properties from controls code behind cannot be used in controls view (.dotcontrol)

### ISSUE THREAD

**Issue by MichalTichy** [riganti/dotvvm#263]
Please add suport for using properties which are declared in controls code behind.

Currently there is now way how to render content of property from controls code behind.

Following sample renders only content of **PropFromViewModel**

_controls markup (.dotcontrol)_
```DOTHTML
@viewModel System.Object, mscorlib
@baseType DotvvmApplication2.Controls.Test, DotvvmApplication2

<p>{{controlProperty: PropFromViewModel}}</p>
<p>{{controlProperty: PropFromControlsCodeBehind}}</p>
<p>{{value:  _control.PropFromControlsCodeBehind}}</p>
```

_Controls code behind_
```c#
public class Test : DotvvmMarkupControl
{
        public string PropFromViewModel
        {
            get { return (string)GetValue(PropFromViewModelProperty); }
            set { SetValue(PropFromViewModelProperty, value); }
        }
        public static readonly DotvvmProperty PropFromViewModelProperty
            = DotvvmProperty.Register<string, Test>(c => c.PropFromViewModel, null);

	    public string PropFromControlsCodeBehind { get; set; } = "This is property from controls code.";
}
```

_page VIEW_
```DOTHTML
<cc:Test PropFromViewModel="{value: "This property is from viewmodel." }" />
```

_result_

**Comment by exyi** [comment]
Currently only dotvvm properties can be used in Javascript, you have to register the property.
```C#
public string MyProperty
{
    get { return (string)GetValue(MyPropertyProperty); }
    set { SetValue(MyPropertyProperty, value); }
}
public static readonly DotvvmProperty MyPropertyProperty
    = DotvvmProperty.Register<string, DefaultControlTreeResolverTests>(c => c.MyProperty, null);
```

Then you can assign it like any other property and it will also work in `value` bindings.
However we should allow normal properties.

**Comment by kiraacorsac** [comment]
I have had very similar issues with properties. I was learning DotVVM from the online video tutorials and slightly modified the tutorial's code.  I have assumed code

_.dotcontrol_
```
<dot:Repeater DataSource="{controlProperty: _control.PossibleRatings}">
    <ItemTemplate>
            <span class="glyphicon glyphicon-star-empty"></span>
    </ItemTemplate>
</dot:Repeater>
```

_control's code behind_
```
public IEnumerable<int> PossibleRatings { get; } = Enumerable.Range(1, 5);
```

would generate the ItemTemplate for each integer, however nothing was rendered. It seems unintuitive. I would have welcomed at least an error message stating I cannot use regular properties in .dotcontrol, especially when you could use the very same snippet in regular View and ViewModel.

**Comment by Mylan719** [comment]
My example:
Lets say I am building Control that renders html based on provided markdown language text:
It should have these properties:
`MarkdownText` - accessible from host view, user of the control sets it by binding
`MarkdownHtml` - computed from `MarkdownText` property , should not be accesible from host view, Its content is rendered in markup part of MarkupControl as `<dot:HtmlLiteral Text='{controlProperty: MarkdownHtml }'>` and I don'tknow if  it makes sense to have it in the ViewModel.

How can I archeve this behavior?

**Comment by exyi** [comment]
@Mylan719 You can modify dotvvm to do that :P. Anyway if you'd be normal user, I'd recommend you to use `[MarkupOptions(MappingMode.Exclude)]` on the dotvvm property.

**Comment by tomasherceg** [comment]
If you use the `controlProperty` binding, the property on the user control must be bound to a viewmodel property, or to a static value.
I am not sure whether it is a good idea to allow to calculate the property value in code, because there is no way how we could update the value on postback without re-rendering the whole control.

**Comment by Mylan719** [comment]
@exyi I dindt know this existed! so this makes the pproperty dissapera from hosting view?
I had discusion about this with @tomasherceg and he points out that there is aanother issue with this approach.
Apparently only way this will work is if such control is set to server rendering.  Because there would be no way to get the computed value to client in client rendering.

**Comment by exyi** [comment]
Maybe we could (re)introduce control state. But it is probably a bit antipatternish, since you can't control the viewmodel data.

**Comment by tomasherceg** [comment]
I don't think it is a good idea to reintroduce the control state. It would depend on a unique control ID generation which is a thing we have tried and weren't much successful.

Finally, we would have to store the control state in the viewmodel (or side by side with it), and I really don't want any control to add anything in the viewstate because that's where you lose control over what data are transferred. That's exactly what killed the Web Forms.

Imagine you have 10kBs of markdown in your viewmodel and have a magic control that can translate it in HTML, store the value in the control state so it can use it in the page. You'll have additional 10kBs in the page state which you need to transfer on postbacks, and now imagine that you use the same control multiple times in the page... That's the point I don't want to reach.

Also, the idea of control state is not compatible with the MVVM principles - the controls are part of the view, so they shouldn't do any difficult logic. 

Additionally, we have the view model nesting feature which allows you to create a special viewmodels for your user controls, use DI and other stuff you might need. I don't think the control state adds something new - the thing you need can be done without it, and it would only complicate the framework and cause potential problems.
