### ISSUE TITLE
Error when binding TextBox to C# DateTime property

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#273]
When i do this binding:
```
<dot:TextBox class="form-control" Type="Date" Text="{value: StartDate}" />
```
```
public DateTime StartDate { get; set; }
```
I get this instead of value that should have been there:
![image](https://cloud.githubusercontent.com/assets/3776116/20614630/18f3e920-b2d1-11e6-9fd5-e9e1aafe16fa.png)

In Knockout context for the form there is:
```
" StartDate": "2016-11-15T02:31:56.0000000"
```

When I change the date using the Date TextBox and make postback (to save it) I get error:
```
Newtonsoft.Json.JsonSerializationExceptionThe value specified in the JSON could not be converted to DateTime!
```

**Comment by tomasherceg** [comment]
For `DateTime` and `Numeric` values, you should do two things:

* Specify the `FormatString`.
* Use the `ValueType` property.

Also, the `Type="Date"` is not a good idea at all because you then rely on the date control in the browser which is hard to use in any real application.


Maybe we could set these properties automatically when the binding points to a `DateTime` or `DateTime?` property. Also, we could provide some reasonable defaults for numeric types.

But if the user binds the property to `object` type, we can't do anything.

**Comment by exyi** [comment]
We should make @Mylan719's code working as expected, noone wants to see weird exception when FormatString and ValueType is not applied. In the new version it will be possible to get return type of a binding which will deprecate the `ValueType` property, we should only make sure that it works correctly without the FormatString.

It could be cool to automatically change `Type` to Date when Text is bound to DateTime. @tomasherceg I don't agree that type="date" is not good idea to use - you can use a Javascript datepicker for unified design anyway with it for desktop, but have not seen usable JS datepicker on a phone.

**Comment by tomasherceg** [comment]
OK, the mobile devices are a good point. 

The rest depends on the new binding system, so when it is done, we can go through this issue.
