### ISSUE TITLE
Support for derived classes or interfaces in ViewModel serializer

### ISSUE THREAD

**Issue by MichalTichy** [riganti/dotvvm#355]
Hi,

it would be really nice to add support for assigning derived object to property whichs type is base object.

something like this:
```C#
    public class SomeViewModel : DotvvmViewModelBase
    {
        public ICollection<BaseObject> SomeObjects { get; set; }

        public override Task Load()
        {
            SomeObjects.Add(new BaseObject());
            SomeObjects.Add(new DeliveredObject());
            return base.Load();
        }
    }
```

**Comment by exyi** [comment]
It is not that simple, because we'd have to either
* maintain `$type` field and resolve the specified class, which is quite bad idea for security - calling any constructor may be bad idea, especially in combination with property to constructor argument mapping (currently not implemented, but proposed). I'm not sure if calling parameterless constructor would be safe, but I don't like it.
* or try to guess which type should be initialized from the present properties (which is infeasible as it will break continuous reading and object population).

I think Newtonsoft.Json solves it somehow, maybe we could use or reimplement that functionality, but I'm not sue how it works. If you have any idea what to do with that, let me know in the comments.

**Comment by tomasherceg** [comment]
Newtonsoft.Json just adds the `$type` field with full type name and the deserialization respects this property. I am not sure if this doesn't impose a security risk - the user can easily exchange the type name to another class or use the error message as a hint to uncover the structure of the application. 
Maybe we could do something like the `KnownType` attribute in WCF - they were used to allow this mechanism for particular types only.

**Comment by djanosik** [comment]
I think we should close this issue. You can use custom JSON converter to handle that.
