### ISSUE TITLE
ServerSide rendering link href

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#360]
I'm trying to create server side rendered links like this;

```
<a RenderSettings.Mode="Server" href="/operation/{value: ID}">Do something</a>
```

The problem I see is that the {value: ID} is not replaced with value, but stays as is {value: ID}

Is it a bug or feature? Generating links on server is a common thing..

**Comment by PavelBansky** [comment]
Ahh! Found it at: https://www.dotvvm.com/docs/tutorials/basics-binding-syntax/latest

The whole href must be in binding href="{value:  "/operation/"+ID}"

**Comment by PavelBansky** [comment]
There is still something fishy.
This works fine

```
 <a RenderSettings.Mode="Server" href="{value:  ID }">Do Something</a>
```

but the expression evaluation doesn't work

```
 <a RenderSettings.Mode="Server" href="{value:  "/operation/" + ID }">Do Something</a>
```
produces this link

/operation/null

**Comment by tomasherceg** [comment]
What version of DotVVM are using? What is the type of the `ID` property?

Btw. there is a RouteLink control you can use to build routes:

```
<dot:RouteLink RouteName="MyRoute" Param-Id="{value: ID}">Do Something</dot:RouteLink>
```

**Comment by exyi** [comment]
If you are using it inside Repeater or simmilar control with `RenderSettings.Mode="Client"`, it may cause this kind of issue. You have to turn server rendering on these too.

**Comment by PavelBansky** [comment]
I'm using 1.1.0.1. I'll try to replicated it on 1.1.1, that was released today.

The ID is a string. I'm using it inside Repeater, but the problem is only when I use 'complex' expressions:
`{value:  "/operation/" + ID }` when I use simply `{value: ID }` it works.

The `<dot:RouteLink>` is nice, but the RouteName has to be hardcoded and can't be assigned in a runtime :(

I have master page where menu items are defined like in a structure bellow. Then in the `master.dothtml` the menu items are populated inside a server side repeater. This allows me to maintain only one List instead of editing the master.dothtml, every time a new menu item is added. Currently this scenario is not working with `<dot:RouteLink>`

```
List<MenuItem> items = List<MenuItem>()
{
  new MenuItem() { Text="Settings", RouteName = "BlockSettings" },
  new MenuItem() { Text="Security", RouteName = "BlockSecurity" },
  new MenuItem() { Text="Notifications", RouteName = "BlockNotification" },
}

public class MenuItem
{
  public string RouteName;
  public string Text;
  public bool Selected;
}
```

**Comment by tomasherceg** [comment]
I cannot see the `ID` property anywhere in the code, but I have noticed that you are using public fields in the `MenuItem` class instead of public properties. Public fields do not serialize in JSON, so they are not available on the client side.

The `MenuItem` class should look like this:

```
public class MenuItem
{
  public string RouteName { get; set; }
  public string Text { get; set; }
  public bool Selected { get; set; }
}
```

P.S. Yes, that's true that the `RouteLink` must have the route name hard coded. If we allow binding to this property, we would need to serialize and send the entire route table to the client (which I wouldn't do because it could uncover many details about the app structure to the potencial attackers).

**Comment by PavelBansky** [comment]
Oh, sorry. Yes I'm using Properties, not field. The code sample was just a dummy code to demonstrate the structure.

The ID is being passed as a parameter in URL. I'll try to replicate the problem with ```<a href="{value: "something" + ID}>``` in a new version of dotVVM.

**Comment by exyi** [comment]
Did the upgrade helped? If not, could you please try to replace the `value`binding with `resource` binding? It is basically a server-side only value binding, so we can se whether the issue is on server or on client side. It this would work, could you also post the translated Javascript? It should look like `"something" + ID()`

**Comment by PavelBansky** [comment]
I can't seemed to repro this with the latest DotVVM. I guess you can close this issue.
Sorry it took a while to test it.

**Comment by tomasherceg** [comment]
No problem, thank you for the report.
