### ISSUE TITLE
RedirectToRoute Results in 'undefined' is not a function (evaluating 'fakeAnchor.click()') - Safari

### ISSUE THREAD

**Issue by peteh1989** [riganti/dotvvm#367]
Hi

I have run into an issue on Safari when using Context.RedirectToRoute.

I have a button click event calling a method with RedirectToRoute as in this example. 

`<dot:Button Click="{{command: ButtonClicked()}}"> Redirect me</dot:Button>`

`        public void ButtonClicked()
        {
            Context.RedirectToRoute("Test");
        }
`

This results in the following error

> `dotvvm--internal:1574TypeError: 'undefined' is not a function (evaluating 'fakeAnchor.click()')`

![dotvvmerror](https://user-images.githubusercontent.com/8647678/27175836-59fc5228-51b8-11e7-9c1b-3831f45c383e.png)

 I'm am using DotVVM version 1.1.2

**Comment by tomasherceg** [comment]
Thanks for the report. 
What version of Safari is that? Mac OS or Windows?

**Comment by peteh1989** [comment]
It's windows version 5.1.7. 
Obviously not a massive use case but i ran into a client who was having issues. 
Just looked and the last release for windows was 2012 so you may deem it too old to support.

**Comment by exyi** [comment]
I'm sorry, but I'd not like support to a non-latest browser. There is
usually no good reason to not upgrade (or use a supported browser) and
a lot of reasons to do it, so I don't see any point in fixing this.
I'd also don't like to accept is as PR, because old-browser
compatibility means less maintainable code and merging one fix would be
a dangerous precedent.

**Comment by tomasherceg** [comment]
I disagree. If the fix is simple like in this case, we should fix it. It is not about Safari, the click event on hyperlink is not present also in older versions of Firefox which may still be out in the world in large companies.

It is true that these things make the code less maintainable, but if the only reason for bad maintainability of DotVVM codebase was the support for various old browsers, I would be super happy. 

DotVVM supports and is tested on IE 11, Edge, Chrome and Firefox.

**Comment by exyi** [comment]
This is assigned to Future release, but there is no point in fixing three years old browser bugs in Future, so I'm closing it.
