### ISSUE TITLE
Simple element without DataContext and attached properties

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#375]
Currently we use `DotvvmBindableObject` as a base class for "elements" like `GridViewColumn` used only for configuration. I think it should not be possible to set `DataContext` and attached properties on these objects. Can we somehow disallow that? Perhaps by creating another base class?

**Comment by exyi** [comment]
Disabling DataContext property will have to disable all DotvvmProperties on the object (bacause binding do require it), which basically means that no feature from DotvvmBindableObject could be moved to the lightweight version of it. So I propose supporting instantiating any objects (inheriting only from `System.Object` in the dothtml markup.

**Comment by exyi** [comment]
Disabling DataContext property will have to disable all DotvvmProperties on the object (bacause binding do require it), which basically means that no feature from DotvvmBindableObject could be moved to the lightweight version of it. So I propose supporting instantiating any objects (inheriting only from `System.Object` in the dothtml markup.

**Comment by tomasherceg** [comment]
The problem of attached properties is where to store them? The `System.Object` does not have the `properties` collection we have in the `DotvvmBindableObject`, so we would have to create another mechanism to persist attacvhed properties and bindings for these object. 
The `GridView*Column` properties can contain bindings. That's why there needs to be the `DotvvmBindableObject` base class right now.

And I am not sure whether we actually need to create an alternate way for this, because there are not many controls which have such complex configuration like the `GridView`. I know that sometimes we need to duplicate properties (`ComboBox` vs `GridViewComboBoxColumn` in the Business Pack), but I don't see it as big deal - WPF does the same thing, Web Forms did the same thing...

**Comment by djanosik** [comment]
You are right. We often need to use bindings on these configuration elements, so we need to inherit from `DotvvmBindableObject`.
