### ISSUE TITLE
Reimplement the postback dispatch mechanism in DotVVM.js

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#390]
Currently, we have a long and very complicated methods in `DotVVM.js` which do postback and static command calls. They are difficult to maintain and extend with new features.
Additionally, the client side events `beforePostback`, `afterPostback` etc. are called in various situations and it is not very clear under what conditions they are fired.

## Requirements

* Return `Promise` for postback and static command. Get rid of the `DotvvmPromise` as it is our custom implementation.
* Reuse as much as possible for static command and postbacks.
* Give every postback a unique id which would be available in all the events.
* Create a new event `postbackStatusChanged` which will fire on all important stages of the postback pipeline (see the next section).
* Support `PostBack.ConcurrencyMode` #283 with an option to have multiple postback queues.

@exyi has made an interesting point, that basically everything is a postback handler. Maybe we should implement the postback dispatching pipeline similarly to OWIN - you register middlewares in the pipeline. One middleware can do the client validation and refuse the postback if there are validation errors, another can fire the postback handlers, another can launch the postback directly or put it in the queue based on the concurrency mode etc.

## PostBack Stages

This is a list of stages for every postback or static command. 

> Feel free to edit the table because I am not sure if the order is right.

1. `started`
2. `postbackHandlersStarted`
3. `postbackHandlersCompleted`
4. `clientValidationStarted`
5. `clientValidationCompleted`
6. `requestReady` (equivalent to `beforePostback` which will stay there for back compat)
7. `responseReceived` 
8. `viewModelUpdating`
9. `viewModelUpdated`
10. `renderedControlsUpdating`
11. `renderedControlsUpdated`
12. `finished` (equivalent to `afterPostback` which will stay there for back compat)

Also, we need an additional states which are not in the pipeline and happen before the `finished` state:

* `rejected` is triggered whenever the postback is interrupted - client validation, cancellation from 
 a postback handler, validation failed on the server. This event should have the `reason` parameter which indicates the reason for the rejection. The promise object will be rejected in this case.
* `error` is triggered when the client-server communication fails, or when the server responds with an exception. The promise object will be rejected in this case.
* `redirect` is triggered when the postback response instructs DotVVM to perform the redirect. The promise object is resolved in this case.

Does this make sense? Feel free to edit this.

**Comment by exyi** [comment]
There is one more complication - how should the planned REST API request works?

**Comment by exyi** [comment]
I have just added some of these events to the `js-postback-refactoring` branch.
* do we need `started`? It's not very clear to me, when should it be invoked. after/before concurrency mode handler? 
* `postbackHandlersStarted` - invoked after concurrency mode handler, before all user postback handlers. And it's basically equivalent to the missing `started`
* `postbackHandlersCompleter` - after all user postback handlers
* I have not added `clientValidationStarted` and `clientValidationCompleted` are a bit problematic because validation is invoked in the `beforePostback` handler, so the order would be undefined.
* `requestReady` is equivalent to `beforePostback`, do we need both?
* `responseReceived` is named `postbackResponseReceived` as it only applies to postbacks, not static commands nor REST api invocations
* I have added `postbackCommitInvoked` rather than `viewModelUpdating`, but it should be equivalent
* `viewModelUpdated` is added
* I don't want to add `renderedControlsUpdating` and `renderedControlsUpdated` as they are deprecated by the VDOM update
* `afterPostback` is invoked when postback is successful, interrupted or error, but not on redirects, SPA redirects, returned files. Is this correct?
* `rejected` - called when the promise is rejected, but it's not an error
* `error` - called when the promise is rejected and it's a network error
* `redirect` - called on redirect, the resulting promise is resolved but returns undefined. Is it correct?

None of these events are called for static commands and REST api invocations, which makes sense as it's a lot different pipeline.

**Comment by exyi** [comment]
Resolved in #428
