### ISSUE TITLE
Stackify Prefix tracing support

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#394]
Similarly to MiniProfiler, we can do an integration with [Stackify Prefix](https://stackify.com/prefix/).

Please upvote if you are interesed.

**Comment by FourFifthsCode** [comment]
This is potentially a show stopper for me. I depend on Prefix heavily in my daily development workflow.

**Comment by tomasherceg** [comment]
Have you tried Prefix in some simple DotVVM app? Which metrics are the most important for you? 
Because DotVVM apps are still .NET or .NET Core apps - Prefix should world there. This issue concerns only supplying additional data to Prefix (e.g. how long the viewmodel serialization took, how long were the Load, PreRender phases etc.).

**Comment by FourFifthsCode** [comment]
My apologies, I didn't realize Prefix needed a different configuration for .NET Core apps. That's why it wasn't showing any data for me. When I launched  the Checkbook sample app, it was showing me requests in prefix with 'module unsupported.' I wrongly assumed it was because of a change in the project settings.

**Comment by exyi** [comment]
Seems that nobody is really interested, so it's not worth the maintenance effort. There is like gazillion of tracing/debugging/monitoring tools and we can't support all we could think of. I have written a documentation page about the interface, so everybody can put those events into any monitoring think they like: https://github.com/riganti/dotvvm-docs/pull/69
