### ISSUE TITLE
Express evaluation in RouteLink

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#409]
I have a following route;

```
config.RouteTable.Add("ScanDetail", "repository/{RepoKey}/scan/{ScanId:long}", "Views/Scans/scandetail.dothtml");
```
and view:

```
<dot:RouteLink RouteName="ScanDetail" Param-RepoKey="{value: UrlFriendlyId}" Param-ScanId="{value: (LastScan == null) ? 0 : LastScan.Id }">
	<dot:Literal Text="{value: LastScan.DateTime}" FormatString="MMMM d, yyyy H:mm" />
</dot:RouteLink>
```

It ends with following error:

```
DotVVM.Framework.Compilation.DotvvmCompilationException: The binding '{ValueBindingExpression: (LastScan == null) ? 0 : LastScan.Id }' is not valid!

System.ArgumentExceptionArgument types do not match

33:    THIS LINE IS IN RED<dot:RouteLink RouteName="ScanDetail" Param-RepoKey="{value: UrlFriendlyId}" Param-ScanId="{value: (LastScan == null) ? 0 : LastScan.Id }">
34:           <dot:Literal Text="{value: LastScan.DateTime}" FormatString="MMMM d, yyyy H:mm" />
35:    </dot:RouteLink>       
```

LastScan.Id is long.

How can I make RouteLink parameters conditional?
btw: This is inside repeater, so some LastScan is null and some not.

**Comment by exyi** [comment]
What happens when you change the `0` literal to `0L`? This may fix the issue on your version of DotVVM, although the conversion seems to be fixed in the `master` branch.

**Comment by PavelBansky** [comment]
The ```0L``` did the trick. 

Is there a plan for IF ELSE statement in views, or the custom controls are the recommended way to go?

**Comment by exyi** [comment]
For simple scenario "Show this panel if <something>, otherwise show another panel" we usually use `Visible` property. In next version of DotVVM, we also plan to introduce `IncludeInPage` property, that will remove the element from DOM, not just hide it, but it will still render the html on server. If you'd like to hide some part of the page completely, I'd recommend writing a custom control. It's not that hard, have a look at [AuthenticatedView](https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Controls/AuthenticatedView.cs) control.
