### ISSUE TITLE
Validation errors are preserved in SPA after going to different route

### ISSUE THREAD

**Issue by Mrnda** [riganti/dotvvm#446]
When filling up form then doing an postback that returns validation errors and then going to a different route the dotvvm.validation.errors() are preserved so all postbacks get aborted.

**Comment by exyi** [comment]
I actually think that we should invalidate these errors before every postback, because it may break on other similar events - I think that removing the object from ViewModel by assigning `null` in staticCommand is enough to break it. But I don't want to simply commit it because the validation is pretty unpredictable... @tomasherceg Do you think it'd be ok?

**Comment by adamjez** [comment]
Fixed in https://github.com/riganti/dotvvm/commit/776e640cec52d888e160529331f81c552561cd4d
