### ISSUE TITLE
GetDotvvmUniqueId

### ISSUE THREAD

**Issue by dotfelixb** [riganti/dotvvm#566]
GetDotvvmUniqueId() throws exception  _Specified method is not supported_

```csharp   
private string GetScriptUniqueId()
{
    var uniqueId = GetDotvvmUniqueId() as string;
    if (uniqueId == null) throw new DotvvmControlException(this, /* Just removed*/);
    return uniqueId;
}
```

Am using the InlineScript control in code, I have a workaround this but why is this throwing this exception?

**Comment by exyi** [comment]
Hi, which (major) version of DotVVM are you using? There are very significant differences in the implementation of this function. And could you please share a stack trace of the exception (you can trim only the dotvvm part)

If you are using version 1.x - there were significant flaws in the binding system and I'm afraid it will be impossible to fix the issue (but it depends)

If you are on the 2.x version - it seems to caused by this line: https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Controls/DotvvmControl.cs#L468
Which basically mean that you have strange object in some parent's `Internal.ClientIDFragmentProperty` property and I assumed that it's impossible. I think that it will be better make this more fault tolerant anyway, thanks for pointing it out :)

**Comment by dotfelixb** [comment]
am on version 2 beta, will investigate and update more on. Thanks

**Comment by quigamdev** [comment]
@dotfelixb Any updates on this issue?
