### ISSUE TITLE
Business Pack GridView does not work with Markup controls, unlike built-in GridView

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#635]
I wanted to encapsulate some html markup placed in `bp:GridViewTemplateColumn`, so I created custom Markup control. When I try to invoke command from some inner controls of it, it throws with:

> System.ExceptionThe control with ID 'c14_0_c33' was not found!

When using built-in GridView in the same scenario, it works as expected, see repro in https://github.com/vstribrny/DotVVM-issues-repro/tree/master/src/BpGridViewAndMarkupControl

Please is there any workaround until it's fixed?

**Comment by exyi** [comment]
That's pretty clearly a bug, thanks for reporting that.

Because it's a problem with command invocation, you can maybe use staticCommand to overcome the issue. If you can't, another possible workaround might be to invoke the command from some component on the main page and hook it through some Javascript. You might create a hidden button that will execute the command and invoke it by calling `click` on it. (note that I have not tested that)


```html
<dot:Button ID="myHackbutton" Visible="false" Click="{command: ...}" />
<the grid....>
   ...
</the grid>
```

and the control:

```html
<button onclick="document.getElementById('myHackbutton').click()" />
```

**Comment by exyi** [comment]
It should be fixed now in `fix/binding-system`. Should be released soon.

**Comment by vstribrny** [comment]
Great! When published, I will test it and provide feedback.

**Comment by exyi** [comment]
This is fixed for a long time, we just forgot to close the issue (AFAIK, please comment if it's still broken in some case)
