### ISSUE TITLE
Place "if" function inside dotmaster

### ISSUE THREAD

**Issue by ezev123** [riganti/dotvvm#735]
Hello, I would like to know if there is a solution in dotvvm regarding placing an "if" inside the dotmaster file or for example inside a dothtml file.

An example of what I would like to work is the following:

   ```
 if (getPermissions ("P") == true)
                     {
                 %>
                 <li class = "dropdown">
                     <a class="dropdown-toggle" data-toggle="dropdown" href="#"> PROFESSIONALS
                             <span class = "caret"> </span> </a>
                     <ul class = "dropdown-menu">
                         <li> <a runat="server" href="~/professionals"> CONSULTATIONS </a> </li>

                     </ul>
                 </li>
                 <%
                     }


                 %>
```

How could I translate that to dotvvm? I await your answer, and thank you very much.

**Comment by exyi** [comment]
That's certainly possible, but there are few ways to conditionally display part of the view. I suppose you are checking a server-side condition and if it's false then the view should not be part of the site at all, in that case you should use `IncludeInPage="{resource: GetPermissions("P") == true}"`. The `resource` binding is basically saying "evaluate this expression and treat is as a constant"

```html
<li class="dropdown" IncludeInPage="{resource: GetPermissions("P") == true}">
    ...
</li>
```

In case you'd want that binding to be updatable, you could use `value` binding, but that has to be evaluatable in Javascript. If you'd be binding to a view model property rather than the function `GetPermissions`, you could use `IncludeInPage="{value: DisplaySomePart}"` and set the property in `PreRender` method. In this case, the HTML will be always included in the page, but it will be hidden at client side.

Also note that we have a control for checking permission - see https://www.dotvvm.com/docs/controls/builtin/AuthenticatedView
