### ISSUE TITLE
Repeater inside table doesn't work without WrapperTagName

### ISSUE THREAD

**Issue by vaclavholusa** [riganti/dotvvm#741]
Hello. 
I tried to build a table with Repeater inside.

```html
<table>
    <thead>
        <tr>
            <th>Base Price</th>
            <th>Price inc. VAT:</th>
        </tr>
    </thead>
    <tbody>
        <dot:Repeater DataSource="{value: CalculatedPrices}">
            <tr>
                <td>
                    <strong><dot:Literal Text="{value: CurrencyCode}" /> <dot:Literal Text="{value: Price}" /> </strong>
                </td>
                <td>
                    <strong><dot:Literal Text="{value: CurrencyCode}" /> <dot:Literal Text="{value: PriceInclVat}" /></strong>
                </td>
            </tr>
        </dot:Repeater>
    </tbody>
</table>
```

This code is throwing an exception inside JS Console

> knockout:75 Uncaught ReferenceError: Unable to process binding "text: function(){return currencyCode }"
Message: currencyCode is not defined
    at text (eval at parseBindingsString (knockout:71), <anonymous>:3:57)
    at c (knockout:71)
    at knockout:74
    at update (knockout:103)
    at a.N.l (knockout:75)
    at Function.dd (knockout:54)
    at Function.ed (knockout:53)
    at Function.ea (knockout:53)
    at Object.a.u.a.N (knockout:51)
    at knockout:75

However slight modification fixes the issue:
```html
<table>
    <thead>
        <tr>
            <th>Base Price</th>
            <th>Price inc. VAT:</th>
        </tr>
    </thead>
    <dot:Repeater DataSource="{value: CalculatedPrices}" WrapperTagName="tbody">
        <tr>
            <td>
                <strong><dot:Literal Text="{value: CurrencyCode}" /> <dot:Literal Text="{value: Price}" /> </strong>
            </td>
            <td>
                <strong><dot:Literal Text="{value: CurrencyCode}" /> <dot:Literal Text="{value: PriceInclVat}" /></strong>
            </td>
        </tr>
    </dot:Repeater>
</table>
```
Removed `<tbody>` and inserted `WrapperTagName` instead.

**Comment by tomasherceg** [comment]
This is a known issue and a limitation of Knockout JS that cannot be fixed easily. 
It's described in the [docs](https://www.dotvvm.com/docs/controls/builtin/Repeater/2.0).

**Comment by tomasherceg** [comment]
Maybe we can add a warning in the Visual Studio Extension that would at least tell the user that this is not supported.

**Comment by exyi** [comment]
Well, here the problem is simply that the Repeater by default renders `div` as the wrapped tag and when `div` is used in the `tbody` tag. The HTML parser tries to fix that, but that only propagates the error to Knockout.js. Unfortunately, there is no way to "fix" this behavior, it's right that "`div` does not work inside `table`". DotVVM can't do basically anything about it, as it has no way of knowing which html tag will the controls produce before they are rendered.

@tomasherceg I remember we were trying to add this kind of warnings into the HTML editor just by providing some metadata into the HTML editor. However, it did not work as it refused to tag "strange" tags by warnings and the "metadata provider" was too hacky to be reliable :/

**Comment by vaclavholusa** [comment]
Aha, the docs are a bit confusing as it states:

> Be careful. Knockout comment bindings don't work well if they are directly in the <table> element. Put the Repeater inside the <tbody> element and it will work.

I just realized that it's related to the part above about `RenderWrapperTag`. Now it's clear. 
Thanks
