### ISSUE TITLE
DotHTML 🔗 JavaScript

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#749]
We were discussing with @tomasherceg @martindybal how to connect JS code and dothtml markup.

We need/want several things:
* Invoke DotVVM `command`s and `staticCommand`s from Javascript code.
* Invoke Javascript functions from event handlers.
* Work with the ViewModel from JS
* Have the functions scoped to one page. We would end up with crazy naming conventions and giant global declarations without the scoping.
* Register some control options for the page (for example a sorting strategy for `bp:AutoComplete`)
* Register postback handers for one page
* Allow the same scoping for markup controls (and maybe also code controls)

We came with an idea, but there is still quite bit of issue to be solved (or ignored). You'd have a JavaScript object that would describe the client-side binding to the dothtml view. The describer object could be a default export of a module specified in a `@js myPage` dothtml directive.

There may be more objects registered for one page, the page should inherit from its master page and controls should inherit from the view they are used in.

## Options

The following properties should be supported:

* `init(HTMLElement)` - a function that is just invoked when the component or page is mounted into the DOM
  - this is not inherited into markup controls
  - the functions are combined as described in https://blog.ploeh.dk/2017/11/06/function-monoids/ (well, just invoked after each other)
  - basically equivalent to `dotvvm.events.init.subscribe(() => ...)` for pages
* `postbackHandlers: [PostbackHandler]` - a collection of postback handlers that are applied by default to all commands in this scope. 
  - basically a scoped version of `dotvvm.globalPostbackHandlers`
  - the order is implicitly that master page is before page, page is before markup control. But it may be overridden by `before` and `after` fields of the postback handler.
* `jsCommands: { [name: string]: (element: HtmlElement, args: [KnockoutObservable<any>]) }` - a dictionary of client side command that may be invoked from the view (see JS Commands below)
  - the dictionaries are concatenated, in case of conflict page overrides master page, control overrides page.
* `requiredNamedCommands: [string]` names of commands that should be imported from the DotHTML into a context
  - this property is there to overcome the issue that command and staticCommands can be only created from DotHTML markup. Also from C# (if you know how to do that), but certainly not from JS.
  - the command will be declared in the page/control in a special control `<dot:NamedCommand Name=nameOfTheCommand Command="{command: DoSomething()}"`
  - it will be later possible to invoke that command from JS.
  - It will return a promise that will contain the result of the command (as compared to the well known hidden button hack)
  - It will be possible to specify command arguments (as compared to the well known hidden button hack)
     - This point is quite important, but it's TODO how to represent that in the control/binding typesystem.
  - This options is not inherited as described above, however the imported commands are inherited.
 - TODO: extend this to support multiple command of the same name (for example with different data context). This can be done easily by distinguishing them by a set of optional ids.

## Context

All function invoked from the options (`init` and commands) will get additional argument with some context. The context will specifically contain:

* `importedCommands: { [name: string]: (args: [any]) => Promise<any>}`
  - Contains the commands imported from `<dot:NamedCommand ...` controls
* `state: any` - in this property, you can store the state of this module. It will be isolated from other instanced of the same markup control.

## JS Commands

We have to figure out how to ergonomically invoke the JavaScript commands from the dothtml markup.

One option is to have `jsCommand` binding that will invoke exactly one command exported from the JS module. Syntax would be `{jsCommand: nameOfTheCommand(Arg1, Arg2, ...)}`, where `nameOfTheCommand` is any identifier and `Arg1...` are the well-known value binding expressions. This way, you can invoke a JS function easily while the arguments are still written in ergonomic way (at least compared to manually unwrapping every knockout observable). The arguments are always passed as knockout observables that may be writable.

Note that all data must be passed arguments, the command does not implicitly get a reference to data context. This is to avoid having commands hidden dependencies that can't be reused anywhere.

Another options is to have a function `_js.Invoke<ResultValue>("commandName", Arg1, Arg2, ...)` that will be used from `staticCommand`. The behavior will be very similar as for the `jsCommand`.

There is always possibility to have both ways supported, as the first one is quite a bit more ergonomic and the second one it a more flexible...

## Issues

* If we let the user work with the client-side viewmodel directly, it will get to an invalid state very easily and don't do any validation here. For example, when you insert your own (naively created) model, client-side validation will stop working (as you'd not specify `$type`).
   - IMHO, we can't leave so many traps in the API. We'll have to give the user a proxy object to the view model that will handle the validation
* We'd like to keep the API strongly typed (in TypeScript), but that depends on the non-existent "TypeScript class generator". This generator then depends on the dotvvm.compiler, which exists, but does not work very well (which is fixable) and needs to run after the build .NET (which is unfixable).

Edits: renamed `commands` to `jsCommands`, `importedCommands` to `requiredNamedCommands`, `importedCommands` to `namedCommands`, `ExportCommand` to `NamedCommand`

**Comment by exyi** [comment]
We had another discussion about this topic today. No final conclusion, but we have got few other ideas:

## Generic postback handler

When you want to run a piece of JS (start/stop animation, for example) before and after a command, there are two ways:
* subscribing for the `dotvvm.events.before/afterPostback`, which is unfortunately global.
* writing, registering and using a postback handler, which is kindof tedious to do.

We could however provide a generic postback handler that would allow you to run any code before/after of the specific command (or on error, maybe some other events). It is an open question whether the code should be a piece of Javascript or any command (static command, old-school command or the new js command).

Both options are of the equal strength and open an easy to use API to launch new command from the postback handler. This may create some non-trivial issues with concurrency-mode deadlocks, the events this system will produce might be ... confusing. Also may lead to unwanted infinite cycles/recursion. I guess it's not preventable by not creating the API, so we'll have to be very careful and detect deadlocks and other misbehavior :/

## Context-scoped exported commands

Commands exported from dothtml into JS are better than the hidden button hack in some sense (you can await the promise). But has limited capabilities in term of scoping - you can have multiple of these button in Repeater and just hit one of them.

We had some proposed API to call exported on a specific context, but I don't remember the specific :/ @tomasherceg could you please repeat that?

It is also questionable if we actually need that, maybe it's yet another thing that will complicate the API. Some use cases might be better solved by passing arguments to the command.

## Tweaks

Maybe we could drop all the sections of the options and only leave there only the exported command. It remains open how whether importing commands should be implicit and if the other options should be dropped or replaced by something.

**Comment by tomasherceg** [comment]
About the exported commands - I was thinking for something like this:
```
<dot:Repeater DataSource="{value:Customers}">
  <dot:ExportCommand Name="cmd1" Command="{command: _root.Delete(_this.Id)}" />
</dot:Repeater>
```
The command would not be exported globally, but in the `$context` variable. Then, we can introduce a JS API to get the command reference:
```
var promise = dotvvm.exportedCommands.invoke("cmd1", sender);
```
The second argument would be a DOM element on which we'll just `ko.contextFor` - I assume that in case of scoped commands the user will have some DOM element (button, link) anyway. 
And if the second argument is omitted, we can just look in the root scope.

**Comment by mrnustik** [comment]
@tomasherceg One feature I am missing from your exported command proposal is an ability to pass parameters from the JS API into the called command.

Common usage scenario for the exported commands is integration with browser or third-party javascript API. For example, when I want to access users location I want to be able to pass the accessed location to the command as a parameter. I would at least like the possibility to alter the parameters in the `invoke()` method call. Something like: 

```
var params = [ "something....", 2];
var promise = dotvvm.exportedCommands.invoke("cmd1", sender, params);
```

Note: I get that there is a workaround when I can add the properties to the ViewModel and update via `dotvvm.viewmodels....`, but it seems like an odd way of doing so.

**Comment by tomasherceg** [comment]
@mrnustik The thing is that command binding evaluates parameters on the server. We basically tell the server which command binding in the page was triggered, and the parameter lookup happens on the server. 
I can imagine this for static commands, but we'd have to think about the syntax to define a placeholder for the parameter that will be supplied from the JavaScript code. Or did you mean to specify just the name of the method without arguments? This can be an issue for overloaded methods (because we won't know how many arguments will come from the JS), but it could work.

**Comment by mrnustik** [comment]
@tomasherceg Oh... I totally forgot about this. If we provide a better way of updating viewmodels from the Javascript we can work without it and use the viewmodel props as a command parameters in the dotHTML.

**Comment by exyi** [comment]
Haha, but there are the other "command parameters" that are probably
only used in some GridView sort expression. The command itself can be a
delegate with parameters and you can use them in the expression by using
the name from delegate.

**Comment by ENgateman** [comment]
@exyi

* Is by "Invoke Javascript functions from event handlers" meant the ability to call JS functions from within `command` and `staticCommand` bindings (i.e. exactly what `jsCommand` is supposed to do)? Otherwise, event handlers in my book are written in JS, so there should be no problem with invoking JS functions from them.

* What exactly is the difference between `commands`, `importCommands`, and `importedCommand`?

**Comment by tomasherceg** [comment]
I was thinking about the `@js` directive - we should allow importing multiple modules and addressing them by an alias. Also, I think that we should name it `@clientModule` instead of just `@js`.

**Comment by exyi** [comment]
> Is by "Invoke Javascript functions from event handlers" meant the ability to call JS functions from within `command` and `staticCommand` bindings.

Calling JS function from command does not make much sense as it's always executed on the server (and we probably can't change that). The meaning is that you put `{staticCommand: _js.myJsFunction(...)}` to any property that expects a command (not only the `command` binding, this might be confusing). The other option is to create another type of command, the `jsCommand` that would be specialized for this purpose.

> (i.e. exactly what jsCommand is supposed to do)

Whenever the syntax would like `{staticCommand: _js.Invoke("myJsFunction", Arg)}`, `{staticCommand: _js.myJsFunction(Arg)}` or `{jsCommand: myJsFunction(Arg)}` it would be translated to something like this (simplified):

```js
dotvvm.applyPostbackHandler(..., () => {
    return dotvvm.jsInterop.invokeJsFunction(
        "myJsFunction",
        [dotvvm.serialization.serialize($data.Arg)
    )
})
```

> Otherwise, event handlers in my book are written in JS, so there should be no problem with invoking JS functions from them.

Which book? Ok, events handlers are always written in JS, but in this context we mean properties of dotvvm controls which type is a delegate. Even though you can always use `<div onclick="myJs" />` it does not allow you to access view model in a sane way, you can't call into a module and this does not work for more complex properties (modal close, some update, ....)

**Comment by exyi** [comment]
> I was thinking about the @js directive - we should allow importing multiple modules and addressing them by an alias.

This basically means that the module can only contain the commands. Other features will be quite unintuitive (IMHO)
* How many times is `init` called when you import the module multiple times?
* The modules should be stateless - otherwise you'll have multiple states for multiple import or single state for multiple aliases.
* Importing commands from dothtml to JS will also be prefixed or not?
   * If not, it can't prevent collisions and I'd expect it to do so.
   * If yes, you can't simply export some command from master page and then use them in a lot of your modules.
* Local postback handlers will also be prefixed? What about postback handler that should have been applied to all controls?
* Without the aliases we thought about tweaking almost any dotvvm option per page from JS. With the scopes, this seems unintuitive.

Maybe these problems might be solved somehow, but there will be some compromises and it's not that easy. 

> Also, I think that we should name it @clientModule instead of just @js.

I kindof like to say explicitly that it's Javascript interop, not some other kind of client-side thing.

**Comment by exyi** [comment]
> What exactly is the difference between `commands`, `importCommands`, and `importedCommand`?

In the original proposal, it was meant:
* Option `commands` are the commands that are written in Javascript and then used in DotHTML
* Option `importCommands` instructs DotVVM to import command from DotHTML to the Javascript. They can be later found in the Context property `importedCommand`. It's there to prevent unwanted dependencies and to be able to check on page load that all required commands are actually exported from DotHTML.
* Context property `importedCommand` contains the commands exported from DotHTML page which name is written in the option `importCommands`.

**Comment by ENgateman** [comment]
Me, @MichalTichy and another person who doesn't with to be tagged just discussed this. We arrived at the following:

* How about we allow public methods on `IDotvvmViewModel` objects to be called wherever, whenever and with whatever parameters (i.e. there doesn't even need to be a command that references this method)? All invocations of such methods would be legal. This would allow us to generate a much nicer TS interface that the programmer can use on the client side.

* If the former is undesirable, parametrization at the  `<dot:ExportCommand />` level is required.

* @tomasherceg In your `<dot:ExportCommand />` sample, how is `sender` to be obtained?

**Comment by exyi** [comment]
> How about we allow public methods on IDotvvmViewModel objects to be called wherever, whenever and with whatever parameters (i.e. there doesn't even need to be a command that references this method)? All invocations of such methods would be legal. This would allow us to generate a much nicer TS interface that the programmer can use on the client side.

methods.

Even when we'd disable "special" methods, it'd break my code (this is not crafted example, the code exists). View model looks like this:

```fsharp
[<Protect(ProtectMode.SignData)>]
member val ComingTransactions : TransactionModel[] = [||] with get, set

member x.AcceptTransaction (transaction:TransactionModel) =
    let (state, teamData) = Helpers.getTeamState x.TeamName
    let spendable = spendableAmount teamData
    for i in transaction.Assets |> Array.filter (fun a -> spendable a.Name + a.Count < int64 0) do
        x.Context.ModelState.Errors.Add(ViewModelValidationError(
            PropertyPath = "Assets",
            ErrorMessage = sprintf "%s: Máš jenom %d" i.Name (spendable i.Name)))
    x.Context.FailOnInvalidModelState()

    StateManager.processUpdate (UpdateMsg.AcceptTransaction transaction.Id)

```
use from the view like this:
```html

<dot:Repeater DataSource="{value: ComingTransactions}">
    ...
    <dot:Button Text="Accept" Click="{command: _root.AcceptTransaction(_this)}" Validation.Enabled="true" />
</dot:Repeater>
```

so it's safe & idiomatic, but the change you propose would allow you to spend assets you don't own.

This would be the most stupid change we have ever made - breaking change not breaking code that worked but breaking security of apps that were perfectly fine (user can safely rely on postbacks being checked).

> If the former is undesirable, parametrization at the <dot:ExportCommand /> level is required.

Sure. All commands support taking arguments. I'm just not sure how will that for the `<dot:ExportCommand />` component

**Comment by tomasherceg** [comment]
I had to read the entire thread from the beginning since it is quite a long time we've been discussed this. 

1. In https://github.com/riganti/dotvvm/issues/749#issuecomment-566500205, @exyi mentions that in case of multiple modules the `init` would be called multiple times, the modules would need to be stateless etc. I think that we'll have to deal with these issues anyway because of SPAs - if the module has some state, shall we keep it when the user does SPA navigation?
The state in the modules is a very interesting thing and could help with many things (for example caching: you can pre-load data from the server and use them instead of calling the server over and over).

2. About the `@js` versus `@clientModule` naming - I'd like to avoid these concrete names as we've been bitten by them many times (e.g. `staticCommand` which doesn't call only static methods, `resource` binding that can call anything, not just RESX entries and so on). 
I feel that this is a similar case - the JS modules can be written in TypeScript (and probably will be as it would help to deal with strong typings) - in principle, they can be anything that runs "locally in the browser". I know that JS will be probably involved, but that's our implementation detail - from the perspective of the user of the framework, I think that `client` makes more sense than `js`.

3. Responding to https://github.com/riganti/dotvvm/issues/749#issuecomment-566555360 - when you need to call a DotVVM command from your JS code, you'll most probably already have the sender (because your code is triggered by some event that is somehow related to the sender), or you'll have an easy way of obtaining it (your code runs after the page is loaded and you interact with some "singleton" stuff in the page). When you call a command from a Knockout binding handler, you have the `element` variable and so on.
I am not against command parameters - I am just wondering how easy they will be to use.
Imagine you need to call something like this: `{command: AddComment(Title, _parent.Category, <someValueFromJs>)}`. 
You'd need to use a delegate in the binding (`{command: AddComment}`) and then pass all the arguments even though the only variable is one of them - so you'd need to call `ko.dataFor(sender).Title()`, `ko.contextFor(sender).$parent.Category()`. That means you'd need the `sender` anyway, and it can be error-prone. 
Supporting lambdas in command bindings would help a lot as you could do this: `{command: x => AddComment(Title, _parent.Category, x)}`.

**Comment by tomasherceg** [comment]
I've put up together a trivial example of a page using a JS module.
https://gist.github.com/tomasherceg/eedd3fce82a28eaaadcb390f1ebdcf53

Basically, it is a page that displays a Google map (`init` methods in the module), allows to add a marker to specified coordinates (calling JS function from a page), and reacts to the clicking on a marker with a postback (calling server from the JS).

I think we should discuss this on a call or in person - I have some observations:

1. We should prepare the TypeScript configuration and "automated" build process for the modules - it must be as simple as adding a TS file in the project and using `@js path_to_the_file` - otherwise it will be too complex.
2. Are `requiredNamedCommands` necessary? Can we just make all named commands declared in the page accessible to the module?
3. Exporting `jsCommands` as an object with a map of functions is quite inconvenient - could we do just `export function MyFunction` and call it from the dothtml page? This will be the most frequent thing to declare so I'd rather keep it as simple as possible. We'll just need some reserved names for other things like `init`, `postBackHandlers` and so on.  
4. In the sample, I found that I need to update the viewmodel from `init` - I think that we'll need to add some way of safe application of changes to the viewmodel - maybe something like `dotvvm.viewModel.patch({ Lat: ..., Lng: ... })` with proper validation.
5. The `jsCommand` methods should get an argument with the context and also with a sender - I am not sure if it should be the first one or the last one, but I guess most of the methods will need both. What about adding sender (or some kind of sender accessor) in the context?

**Comment by exyi** [comment]
This was pretty much done in 3.0 and further extended in 4.0 with JsComponents and validation API. I don't think there is much left to be done from this issue.
