### ISSUE TITLE
Allow use of a read-only variable in static command bindings

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#776]
Some time ago I've found myself  in a situation where I wanted to update multiple viewmodel properties in one button click. I wanted to load both user information and a shopping cart content to fill the top panel of my page when a button is clicked.
Let's have a viewmodel:
```csharp
public class ThePage
{
    public ShopingCartViewModel ShoppingCart { get; set; }
    public UserInfo { get; set; }
    //...
}
```
Of course the viewmodel contains lots of other properties, and I don't want to drag them all to the server side and back just because I need to update 2 properties...
...so I used a service with contract like this:
```csharp
public class PanelInfoDto{
    public ShopingCartViewModel ShoppingCart { get; set; }
    public UserInfo { get; set; }
}

public interface IPanelInfoService
{
    ShopingCartViewModel  GetShoppingCart();
    UserInfo  GetUserInfo();
    PanelInfoDto GetPanelInfo();
}
```
I realized, that there is no practical way to update two properties at once using single service call inside of static command.

Only 2 ways to solve this now:

1.  Using two calls: `staticCommand: ShoppingCart = service.GetShoppingCart(); UserInfo = service.GetUserInfo()`. This is less then ideal because I need to make 2 calls to the server which is slower. This method does not work for all cases. There are operations that require updating multiple properties which cannot be repeated (Save, Refresh of items,...).

2. Using temporary viewmodel property: `staticCommand: Temp = service.GetPanelInfo(); UserInfo = Temp.UserInfo(); ShoppingCart = Temp.ShoppingCart`. This method also works for operations that cannot be repeated. However I find it clunky and hard on an unfamiliar reader.

My proposed solution:
```html
<dot:Button Text="Update" 
            Click="{staticCommand: let info = service.GetPanelInfo(); 
                                              UserInfo = info.UserInfo(); 
                                              ShoppingCart = info.ShoppingCart}" />
```
Read-only binding local variable that would be defined in the first statement and could be used in all following statements  in the same binding.

This variable would be also useful in following use cases:

- saving data and getting updated repeater items back together with success/error message
- updating 2 grids at once
- updating grid and filling items of dependent combo-boxes at the same time
- updating multiple filters that depend on each others values

**Comment by tomasherceg** [comment]
My first impression is that I don't like variables in the bindings. But on the second thought, it makes sense and it is certainly better than using a temp property in the viewmodel (which is possible right now).

I think that we should look at this from a larger perspective. We don't actually need variables in static commands - we need static commands to be more powerful and we need them to contain more complex logic.

We had several attempts to add an option to call JavaScript or TypeScript methods, we were thinking about the integration with web assembly to be able to call various workloads from the viewmodels. We even had an implementation of translating C# code to JavaScript which is not finished.

When I look at Blazor, it brought back the approach that you include code and declarations in the views - there is the `@code` section which allows declaring custom methods and properties.

What about doing something like this:
```
<dot:Button Click="{staticCommand: _client.LoadPanelInfo()}" ... />
...
<dot:ClientState> 
// we can allow just one section per view - it would expose _client variable in the bindings
// it might also contain public properties for client-only state and auto-bind events like Init, BeforePostback and so on
// there can by this.ViewModel, this.Context and other things to read page metadata or to interact with the page
public PanelInfo LoadPanelInfo() {
  var info = _service.GetPanelInfo();   // service is dependency injected from the constructor
  this.ViewModel.UserInfo = info.UserInfo; 
  this.ViewModel.ShoppingCart = info.ShoppingCart
}
</dot:ClientState>
```

All expressions in these classes would be translated using static commands logic, and it makes sense to support variables, ifs, foreach loops and other things here.

But there might be other solutions to the variable problem - for example tuples and deconstruction:
```
<dot:Button Click="{staticCommand: (UserInfo, ShoppingCart) = _service.PanelInfo()}" ... />
```

That's why I think this needs some conversation which way we'd like to choose.

**Comment by tomasherceg** [comment]
@martindybal This doesn't support `Property.Property = something`, but instead of calling `Context.UpdateProperties` we can return something like `ViewModelPatch<T>`:
```
return new ViewModelPatch<T>(vm => vm.UserInfo = "aaa", vm => vm.ShoppingCart = cart);
```
And then call it like this:
```
{staticCommand: _page.patch(_this, _service.GetPanelInfo())}
```
We might also detect that we are adding or removing items from the collection and serialize the `ViewModelPatch` object so we can repeat the operation in JS.

**Comment by exyi** [comment]
> @tomasherceg's proposal about `<dot:ClientState>`
> All expressions in these classes would be translated using static commands logic, and it makes sense to support variables, ifs, foreach loops and other things here.

The problem with this obvious - it is very a complex task to implement (without significant compromises).

> `Context.UpdateProperties(nameof(UserInfo), nameof(ShoppingCart));`

And what is the object where you are updating these properties? It is the current root ViewModel or some of the parameters? In either case, I hate the idea that the function would have hidden dependencies on some data context.

Returning the `ViewModelPath<T>` make much more sense in a sense, but still... the dependency on the actual type where the result got assigned actually did not have to exist at all. Suppose you want to have a command that load an object with a specified pattern, but it may also fail and return a message. You'd probably have it return `{ Obj: SomeViewModel, Message: string}`. Then you can assign the error message and object anywhere you want on every page, instead of overloading one `string Message` property from some base view model.

Maybe having variables in a command looks like putting logic into view, but that's not what the intended use case is. The point is simply to pipe data from a function to the view model, so the function does not have to be bound to the view model (and vice versa).

Another concern should be that variables are also usable in REST API bindings, while some strange `ViewModelPatch<T>` will hardly be useful.

**Comment by martindybal** [comment]
Another idea, maybe we can add "method block" to view. If there no simple way how to write it in C#, we can add something like this:
```
<%-- This is not C# code, it's static command expression in block for better readability--%>
<StaticCommandMethod Name="MyStaticCommand">
    var result = await service.GetPanelInfo(); //I think await is better then .Result
    UserInfo = result .UserInfo; 
    ShoppingCart = result .ShoppingCart
</StaticCommandMethod>
<dot:Button Text="Update" Click="{staticCommand: MyStaticCommand}" />
```

**Comment by tomasherceg** [comment]
This is basically what I've suggested several comments above: https://github.com/riganti/dotvvm/issues/776#issuecomment-541613219

The main issue I see in this approach is that people would think that it's regular C# and expect to behave it like C#, which won't be true. Maybe we could create a Roslyn analyzer to underscore everything that is not supported.

**Comment by martindybal** [comment]
Sorry, I totally missed that. Yes, that could be misleading. But it's better then long expression in one line.

**Comment by exyi** [comment]
> maybe we can add "method block" to view.

That would only make sense if that logic repeats multiple times or if there is a good reason to name the logic. I don't think any of these is often the case (?)

Also, you'd have to specify in which data context may the "method" be used (including the parent and such)

> `await service.GetPanelInfo(); //I think await is better then .Result`

This actually a good point, it should not be too much work to add support for await to the parser / compiler

> But it's better then long expression in one line.

Is there anything forcing you to have it on one line? This should work just fine.

```html
<dot:Button Text="Abc"
            Click={staticCommand:
                var x = M();
                _this.A = x.A;
                _parent.B = x.B;
            } />

```

**Comment by martindybal** [comment]
@exyi 
1) Yes, in my case it's repeat. Context don't have to be tricky. We can use same logic as for alle other controls. If you want to change context, you can move `StaticCommand` or you can use `_parent.MyStaticCommand`
1)  great :)
1) I tried that, but I don't like. The view is too long and complicated. From my point of view is better to have all static command at the beginning of the view. Plus point 1

**Comment by exyi** [comment]
> you can move StaticCommand

Then you don't have them at the beginning of the view.

And, you might have a command binding in a different data context than is the control (using DataContextChange attributes), in that case you might be unable to declare the method in the right data context.

There would be significant advantages to the declared methods, however. If we allow assigning to a array and recursion, we will be finally able to implement anything in the view :sunglasses:, without user clicking to run the state machine :D

**Comment by tomasherceg** [comment]
I can see a lot of advantages in having the option to declare methods and call them from static commands, and the truth is that this approach (having C# code translated into JS) is the authentic "DotVVM" way of doing things (in both good and bad meaning: good = it would be super-easy for the users, bad = it would have a lot of limitations and glitches). 

As I already mentioned on the last sync call, I think that we should allow the variable declarations in the binding expressions, but I think that we shouldn't end with just that. 
We need either JS modules (which would be more powerful but a little harder for the users) or this `ClientState/StaticCommand/whatever` control that will allow declaring methods in the views that could be called, in order to avoid multi-statement binding expressions.
