### ISSUE TITLE
Ignore exceptions when traversing assemblies which are not found

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#778]
DotVVM traverses all assemblies recursively during application startup, but there are many disadvantages in this approach.

1. I got a report from a customer - basically he is using some 3rd party libraries which reference inexistent DLLs and our code tries to load them aggressively.
2. Traversing everything slows the startup (especially in Azure). Maybe we could offer some way to disable the auto-loading and manually register assemblies that contain DotVVM properties instead.

**Comment by exyi** [comment]
Since controls must be registered anyway, maybe we could only load assemblies that contain registred controls. This may break some strange cases (when you have only attached properties inside the assembly), but that's an unlikely issue.

I doubt it will help the startup time anyway as you'll load most of the dependencies anyway, just a second later.

**Comment by exyi** [comment]
@tomasherceg Isn't this basically resolved by the explicit assembly loading?

**Comment by exyi** [comment]
This is what explicit assembly loading solves. If there is something missing, please create a different issue
