### ISSUE TITLE
Client side changes are discarded by postback 

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#827]
Client view model changes are discarded by postback even if data wasn't change on server. I prepare simple repro. [ClientViewModelChangeRepro.zip](https://github.com/riganti/dotvvm/files/4532350/ClientViewModelChangeRepro.zip)

**Comment by exyi** [comment]
Yes, this is how it works ¯\_(ツ)_/¯ The reason is simply, that merging changes from client and server is super complicated.

Any way of doing a 3-way merge on original viewmodel, the client-side changes and server-side changes will inherently lead to strange behavior. Doing distributed data structures (i.e. object that can be changed on both client and server) is a inherently complex topic, and we are out of luck since we allow any modification of the object on both nodes.

It's not only about ignoring the unchanged properties, since you can, for example, change a property in an object that was completely removed on the client while the postback was running. This could still be ok, if the object was replaced by null, but suppose you have a collection of objects:

* the user can reorder them however they want, this happens on client-side
* they can press a refresh button, that reloads new information from the server into the objects.

So the user presses refresh button and `Items[0].Name` is updates with new text. In the meantime, they also change the order. However, this still means that `Items[0].Name` will be updated, which is now a different item. I don't see any way around this. Maybe it seems as an artificial counterexample, but this will occur in practice, just not in such simple cases...

Maybe it's a better compromise, but I think we should rather avoid complicating the behavior. We can however:

* Not revert changes in properties with `[Bind(Direction.ServerToClientFirstRequest)]`
* Freeze all other properties during postback (this is however not very well possible with knockout :/ )
* Make static commands more powerful, so you can avoid postbacks esp. for background operations (stuff like #776)

**Comment by exyi** [comment]
I will close this, since we are not going to "fix it". As I explained, merging changes from server and client would only lead to more crazy things happening. You can however:

* Use `staticCommand`, esp. for background operations.
* Use `[Bind(Direction.ServerToClientFirstRequest)]`, these properties are not going to be reverted.
* Use `FormControls.Enabled={value: !_page.IsPostbackRunning}` to prevent user from changing the properties if a postback is running.
