### ISSUE TITLE
ResponsiveNavigation: Alt image text not working

### ISSUE THREAD

**Issue by Lixfeld** [riganti/dotvvm#929]
The behaviour of the HeaderText for the ResponsiveNavigation control is not working: 

> HeaderText: Gets or sets text that will be put in header. If HeaderImage is set this text will be used as alternate image text.

The second example in the [documentation page](https://www.dotvvm.com/docs/controls/bootstrap4/ResponsiveNavigation/2.0) is also not working:
```
<bs:ResponsiveNavigation 
        HeaderImageUrl="~/Images/person.png" 
        HeaderText="Alt text for image" 
        HeaderLinkUrl="http://www.dotvvm.com" 
        Theme="Dark" 
        ScrollBehavior="StickyTop">

    <bs:NavigationItem NavigateUrl="https://www.google.com/" Text="Google" />
    <bs:NavigationItem NavigateUrl="http://www.w3schools.com/html/" Text="W3 Schools" />
</bs:ResponsiveNavigation>
```
![image](https://user-images.githubusercontent.com/57292635/104854191-a998bd00-5905-11eb-9e9d-c9408de53358.png)

**Comment by MichalTichy** [comment]
Thank you for the bug report.

I've added two new properties to ResponsiveNavigation: HeaderImageAltText, HeaderImageTooltip. And modified doc to reflect those changes.

Unfortunately we could not modify the code to work as was previously described in the doc because this would break a lot of people.

The new version 2.5.1 is now available at the DotVVM nuget.
