### ISSUE TITLE
Add a mechanism to validate the entire control tree

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#99]
We need a mechanism which can browse the whole control tree and validate it, before the page is being rendered.
We need this to check duplicate IDs of controls etc.

Each control should be able to register its own validator for the control tree and we need to make sure that the validation will be executed only once.

Then, we need to implement the following validation rules:
1) Make sure that IDs of controls are unique.
2) Make sure that all RadioButtons in the same group are bound to the same viewmodel property and make sure that all of them use either the Checked binding, or the CheckedItem binding. The second one applies also to the CheckBoxes.

**Comment by exyi** [comment]
Do you want to run this at compile time on the Resolved Control Tree or at runtime before Render event? It would be quite good idea to have both options, because something can't be validated at compile time (value comes from binding). And when we can say that something is wrong at compile time IDE could underline it as error. And it is much easier to compile all pages to test whole project for errors than UI test all of them.

**Comment by tomasherceg** [comment]
Solved partially by `ValidateControlUsage`. 
Duplicity of IDs is not so important as they changed their meaning since the issue was created.
